#!/bin/bash
echo $1 > output
echo fejl-rapport >> output
./visfejl.sh >> output
echo "####" >> output
echo "####" >> output
echo XML-fejl-rapport >> output
./check_failed_xml.sh "$1" >> output
T=$1
echo "####" >> output
echo "####" >> output
cat log >> output
cp output output.txt
echo "see attachment" | mail -s"$T" -a output.txt dla@statsbiblioteket.dk,kfc@statsbiblioteket.dk,mfo@statsbiblioteket.dk

